// This file contains the icon registry for the application. And is used to register all the icons in the application.

const iconsRegistry = [
  'test',
  'admin',
  'calendar',
  'camera',
  'capture',
  'caret',
  'chevron',
  'close',
  'comment',
  'control-button',
  'control-keyboard',
  'control-table',
  'control-textfield',
  'copy',
  'details',
  'directory',
  'execution',
  'export',
  'file-data',
  'flow',
  'folder',
  'grip-bar',
  'import',
  'info',
  'magic',
  'mobile',
  'not-ok',
  'ok',
  'paste',
  'pen',
  'play-outline',
  'plus-icon',
  'queued',
  'report',
  'repository',
  'right-arrow',
  'screen',
  'search-icon',
  'suite',
  'terminated',
  'test-case',
  'tools',
  'trash',
  'type-web',
  'upload',
  'utilities',
  'wait',
] as const

export type IconName = (typeof iconsRegistry)[number]

export default iconsRegistry
