export type TreeNode = {
  id: string
  name: string
  variant: 'file' | 'folder'
  nodes: TreeNode[]
  data?: {
    id: string
    name: string
    email: string
    phone: string
    address: string
    age: number
  }[]
}

export type Tree = TreeNode[]

export const folderTree: TreeNode[] = [
  {
    id: '1',
    name: 'folder 1',
    variant: 'folder',
    nodes: [
      {
        id: '2',
        name: 'folder 2',
        variant: 'folder',
        nodes: [
          {
            id: '3',
            name: 'folder 3',
            variant: 'folder',
            nodes: [
              {
                id: '4',
                name: 'file 1',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe',
                    email: 'john.doe@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 12,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe2',
                    email: 'jane.doe12@google.com',
                    phone: '1234567890',
                    address: '123 Main St, Anytown, USA',
                    age: 25,
                  },
                  {
                    id: '3',
                    name: 'Alice Smith',
                    email: 'alice.smith@example.com',
                    phone: '9876543210',
                    address: '456 Elm St, Springfield, USA',
                    age: 30,
                  },
                  {
                    id: '4',
                    name: 'Bob Johnson',
                    email: 'bob.johnson@example.com',
                    phone: '5555555555',
                    address: '789 Oak St, Metropolis, USA',
                    age: 40,
                  },
                  {
                    id: '5',
                    name: 'Charlie Brown',
                    email: 'charlie.brown@example.com',
                    phone: '1112223333',
                    address: '321 Pine St, Gotham, USA',
                    age: 22,
                  },
                  {
                    id: '6',
                    name: 'Diana Prince',
                    email: 'diana.prince@example.com',
                    phone: '4445556666',
                    address: '654 Maple St, Star City, USA',
                    age: 28,
                  },
                  {
                    id: '7',
                    name: 'Ethan Hunt',
                    email: 'ethan.hunt@example.com',
                    phone: '7778889999',
                    address: '987 Cedar St, Central City, USA',
                    age: 35,
                  },
                  {
                    id: '8',
                    name: 'Fiona Gallagher',
                    email: 'fiona.gallagher@example.com',
                    phone: '2223334444',
                    address: '159 Birch St, Coast City, USA',
                    age: 27,
                  },
                  {
                    id: '9',
                    name: 'George Costanza',
                    email: 'george.costanza@example.co',
                    phone: '3334445555',
                    address: '753 Walnut St, Smallville, USA',
                    age: 31,
                  },
                  {
                    id: '10',
                    name: 'Hannah Baker',
                    email: 'hannah.baker@example.com',
                    phone: '6667778888',
                    address: '852 Spruce St, Hill Valley, USA',
                    age: 19,
                  },
                ],
                nodes: [],
              },
              {
                id: '5',
                name: 'file 2',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe12312',
                    email: 'john.doe324@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 56,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe243423',
                    email: 'jane.doe122@example.com',
                    phone: '123213123',
                    address: '1223 New Street, USA',
                    age: 34,
                  },
                  {
                    id: '3',
                    name: 'Ivy League',
                    email: 'ivy.league@example.com',
                    phone: '5556667777',
                    address: '123 Ivy St, Ivy Town, USA',
                    age: 29,
                  },
                  {
                    id: '4',
                    name: 'Jack Sparrow',
                    email: 'jack.sparrow@example.com',
                    phone: '8889990000',
                    address: '456 Pirate Cove, Caribbean, USA',
                    age: 45,
                  },
                  {
                    id: '5',
                    name: 'Kara Danvers',
                    email: 'kara.danvers@example.com',
                    phone: '1112223333',
                    address: '789 Fortress St, National City, USA',
                    age: 26,
                  },
                  {
                    id: '6',
                    name: 'Leonard William',
                    email: 'leonard.william@example.com',
                    phone: '4445556666',
                    address: '321 Science St, Pasadena, USA',
                    age: 33,
                  },
                  {
                    id: '7',
                    name: 'Monica Geller',
                    email: 'monica.geller@example.com',
                    phone: '7778889999',
                    address: '654 Coffee St, New York, USA',
                    age: 30,
                  },
                  {
                    id: '8',
                    name: 'Nina Williams',
                    email: 'nina.williams@example.com',
                    phone: '2223334444',
                    address: '159 Fighter St, Tokyo, Japan',
                    age: 24,
                  },
                  {
                    id: '9',
                    name: 'Oscar Isaac',
                    email: 'oscar.isaac@example.com',
                    phone: '3334445555',
                    address: '753 Actor St, Hollywood, USA',
                    age: 36,
                  },
                  {
                    id: '10',
                    name: 'Penny Lane',
                    email: 'penny.lane@example.com',
                    phone: '6667778888',
                    address: '852 Music St, Liverpool, UK',
                    age: 22,
                  },
                ],
                nodes: [],
              },
              {
                id: '6',
                name: 'file 3',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe',
                    email: 'john.doe@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 12,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe2',
                    email: 'jane.doe12@google.com',
                    phone: '1234567890',
                    address: '123 Main St, Anytown, USA',
                    age: 25,
                  },
                  {
                    id: '3',
                    name: 'Alice Smith',
                    email: 'alice.smith@example.com',
                    phone: '9876543210',
                    address: '456 Elm St, Springfield, USA',
                    age: 30,
                  },
                  {
                    id: '4',
                    name: 'Bob Johnson',
                    email: 'bob.johnson@example.com',
                    phone: '5555555555',
                    address: '789 Oak St, Metropolis, USA',
                    age: 40,
                  },
                  {
                    id: '5',
                    name: 'Charlie Brown',
                    email: 'charlie.brown@example.com',
                    phone: '1112223333',
                    address: '321 Pine St, Gotham, USA',
                    age: 22,
                  },
                ],
                nodes: [],
              },
              {
                id: '7',
                name: 'file 4',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'Diana Prince',
                    email: 'diana.prince@example.com',
                    phone: '4445556666',
                    address: '654 Maple St, Star City, USA',
                    age: 28,
                  },
                  {
                    id: '2',
                    name: 'Ethan Hunt',
                    email: 'ethan.hunt@example.com',
                    phone: '7778889999',
                    address: '987 Cedar St, Central City, USA',
                    age: 35,
                  },
                  {
                    id: '3',
                    name: 'Fiona Gallagher',
                    email: 'fiona.gallagher@example.com',
                    phone: '2223334444',
                    address: '159 Birch St, Coast City, USA',
                    age: 27,
                  },
                  {
                    id: '4',
                    name: 'George Costanza',
                    email: 'george.costanza@example.co',
                    phone: '3334445555',
                    address: '753 Walnut St, Smallville, USA',
                    age: 31,
                  },
                  {
                    id: '5',
                    name: 'Hannah Baker',
                    email: 'hannah.baker@example.com',
                    phone: '6667778888',
                    address: '852 Spruce St, Hill Valley, USA',
                    age: 19,
                  },
                ],
                nodes: [],
              },
            ],
          },
          {
            id: '8',
            name: 'folder 4',
            variant: 'folder',
            nodes: [
              {
                id: '9',
                name: 'file 5',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe',
                    email: 'john.doe@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 12,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe2',
                    email: 'jane.doe12@google.com',
                    phone: '1234567890',
                    address: '123 Main St, Anytown, USA',
                    age: 25,
                  },
                  {
                    id: '3',
                    name: 'Alice Smith',
                    email: 'alice.smith@example.com',
                    phone: '9876543210',
                    address: '456 Elm St, Springfield, USA',
                    age: 30,
                  },
                  {
                    id: '4',
                    name: 'Bob Johnson',
                    email: 'bob.johnson@example.com',
                    phone: '5555555555',
                    address: '789 Oak St, Metropolis, USA',
                    age: 40,
                  },
                  {
                    id: '5',
                    name: 'Charlie Brown',
                    email: 'charlie.brown@example.com',
                    phone: '1112223333',
                    address: '321 Pine St, Gotham, USA',
                    age: 22,
                  },
                ],
                nodes: [],
              },
              {
                id: '10',
                name: 'file 6',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'Diana Prince',
                    email: 'diana.prince@example.com',
                    phone: '4445556666',
                    address: '654 Maple St, Star City, USA',
                    age: 28,
                  },
                  {
                    id: '2',
                    name: 'Ethan Hunt',
                    email: 'ethan.hunt@example.com',
                    phone: '7778889999',
                    address: '987 Cedar St, Central City, USA',
                    age: 35,
                  },
                  {
                    id: '3',
                    name: 'Fiona Gallagher',
                    email: 'fiona.gallagher@example.com',
                    phone: '2223334444',
                    address: '159 Birch St, Coast City, USA',
                    age: 27,
                  },
                  {
                    id: '4',
                    name: 'George Costanza',
                    email: 'george.costanza@example.co',
                    phone: '3334445555',
                    address: '753 Walnut St, Smallville, USA',
                    age: 31,
                  },
                  {
                    id: '5',
                    name: 'Hannah Baker',
                    email: 'hannah.baker@example.com',
                    phone: '6667778888',
                    address: '852 Spruce St, Hill Valley, USA',
                    age: 19,
                  },
                ],
                nodes: [],
              },
              {
                id: '11',
                name: 'file 7',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe12312',
                    email: 'john.doe324@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 56,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe243423',
                    email: 'jane.doe122@example.com',
                    phone: '123213123',
                    address: '1223 New Street, USA',
                    age: 34,
                  },
                  {
                    id: '3',
                    name: 'Ivy League',
                    email: 'ivy.league@example.com',
                    phone: '5556667777',
                    address: '123 Ivy St, Ivy Town, USA',
                    age: 29,
                  },
                  {
                    id: '4',
                    name: 'Jack Sparrow',
                    email: 'jack.sparrow@example.com',
                    phone: '8889990000',
                    address: '456 Pirate Cove, Caribbean, USA',
                    age: 45,
                  },
                  {
                    id: '5',
                    name: 'Kara Danvers',
                    email: 'kara.danvers@example.com',
                    phone: '1112223333',
                    address: '789 Fortress St, National City, USA',
                    age: 26,
                  },
                ],
                nodes: [],
              },
              {
                id: '12',
                name: 'file 8',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'Leonard William',
                    email: 'leonard.william@example.com',
                    phone: '4445556666',
                    address: '321 Science St, Pasadena, USA',
                    age: 33,
                  },
                  {
                    id: '2',
                    name: 'Monica Geller',
                    email: 'monica.geller@example.com',
                    phone: '7778889999',
                    address: '654 Coffee St, New York, USA',
                    age: 30,
                  },
                  {
                    id: '3',
                    name: 'Nina Williams',
                    email: 'nina.williams@example.com',
                    phone: '2223334444',
                    address: '159 Fighter St, Tokyo, Japan',
                    age: 24,
                  },
                  {
                    id: '4',
                    name: 'Oscar Isaac',
                    email: 'oscar.isaac@example.com',
                    phone: '3334445555',
                    address: '753 Actor St, Hollywood, USA',
                    age: 36,
                  },
                  {
                    id: '5',
                    name: 'Penny Lane',
                    email: 'penny.lane@example.com',
                    phone: '6667778888',
                    address: '852 Music St, Liverpool, UK',
                    age: 22,
                  },
                ],
                nodes: [],
              },
            ],
          },
          {
            id: '13',
            name: 'folder 5',
            variant: 'folder',
            nodes: [
              {
                id: '14',
                name: 'file 9',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe',
                    email: 'john.doe@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 12,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe2',
                    email: 'jane.doe12@google.com',
                    phone: '1234567890',
                    address: '123 Main St, Anytown, USA',
                    age: 25,
                  },
                  {
                    id: '3',
                    name: 'Alice Smith',
                    email: 'alice.smith@example.com',
                    phone: '9876543210',
                    address: '456 Elm St, Springfield, USA',
                    age: 30,
                  },
                  {
                    id: '4',
                    name: 'Bob Johnson',
                    email: 'bob.johnson@example.com',
                    phone: '5555555555',
                    address: '789 Oak St, Metropolis, USA',
                    age: 40,
                  },
                  {
                    id: '5',
                    name: 'Charlie Brown',
                    email: 'charlie.brown@example.com',
                    phone: '1112223333',
                    address: '321 Pine St, Gotham, USA',
                    age: 22,
                  },
                ],
                nodes: [],
              },
              {
                id: '15',
                name: 'file 10',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'Diana Prince',
                    email: 'diana.prince@example.com',
                    phone: '4445556666',
                    address: '654 Maple St, Star City, USA',
                    age: 28,
                  },
                  {
                    id: '2',
                    name: 'Ethan Hunt',
                    email: 'ethan.hunt@example.com',
                    phone: '7778889999',
                    address: '987 Cedar St, Central City, USA',
                    age: 35,
                  },
                  {
                    id: '3',
                    name: 'Fiona Gallagher',
                    email: 'fiona.gallagher@example.com',
                    phone: '2223334444',
                    address: '159 Birch St, Coast City, USA',
                    age: 27,
                  },
                  {
                    id: '4',
                    name: 'George Costanza',
                    email: 'george.costanza@example.co',
                    phone: '3334445555',
                    address: '753 Walnut St, Smallville, USA',
                    age: 31,
                  },
                  {
                    id: '5',
                    name: 'Hannah Baker',
                    email: 'hannah.baker@example.com',
                    phone: '6667778888',
                    address: '852 Spruce St, Hill Valley, USA',
                    age: 19,
                  },
                ],
                nodes: [],
              },
              {
                id: '16',
                name: 'file 11',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe12312',
                    email: 'john.doe324@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 56,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe243423',
                    email: 'jane.doe122@example.com',
                    phone: '123213123',
                    address: '1223 New Street, USA',
                    age: 34,
                  },
                  {
                    id: '3',
                    name: 'Ivy League',
                    email: 'ivy.league@example.com',
                    phone: '5556667777',
                    address: '123 Ivy St, Ivy Town, USA',
                    age: 29,
                  },
                  {
                    id: '4',
                    name: 'Jack Sparrow',
                    email: 'jack.sparrow@example.com',
                    phone: '8889990000',
                    address: '456 Pirate Cove, Caribbean, USA',
                    age: 45,
                  },
                  {
                    id: '5',
                    name: 'Kara Danvers',
                    email: 'kara.danvers@example.com',
                    phone: '1112223333',
                    address: '789 Fortress St, National City, USA',
                    age: 26,
                  },
                ],
                nodes: [],
              },
            ],
          },
          {
            id: '17',
            name: 'file 12',
            variant: 'file',
            data: [
              {
                id: '1',
                name: 'Leonard William',
                email: 'leonard.william@example.com',
                phone: '4445556666',
                address: '321 Science St, Pasadena, USA',
                age: 33,
              },
              {
                id: '2',
                name: 'Monica Geller',
                email: 'monica.geller@example.com',
                phone: '7778889999',
                address: '654 Coffee St, New York, USA',
                age: 30,
              },
              {
                id: '3',
                name: 'Nina Williams',
                email: 'nina.williams@example.com',
                phone: '2223334444',
                address: '159 Fighter St, Tokyo, Japan',
                age: 24,
              },
              {
                id: '4',
                name: 'Oscar Isaac',
                email: 'oscar.isaac@example.com',
                phone: '3334445555',
                address: '753 Actor St, Hollywood, USA',
                age: 36,
              },
              {
                id: '5',
                name: 'Penny Lane',
                email: 'penny.lane@example.com',
                phone: '6667778888',
                address: '852 Music St, Liverpool, UK',
                age: 22,
              },
            ],
            nodes: [],
          },
          {
            id: '18',
            name: 'file 13',
            variant: 'file',
            data: [
              {
                id: '1',
                name: 'John Doe',
                email: 'john.doe@example.com',
                phone: '324242423',
                address: '1223 New York, USA',
                age: 12,
              },
              {
                id: '2',
                name: 'Jane Doe2',
                email: 'jane.doe12@google.com',
                phone: '1234567890',
                address: '123 Main St, Anytown, USA',
                age: 25,
              },
              {
                id: '3',
                name: 'Alice Smith',
                email: 'alice.smith@example.com',
                phone: '9876543210',
                address: '456 Elm St, Springfield, USA',
                age: 30,
              },
              {
                id: '4',
                name: 'Bob Johnson',
                email: 'bob.johnson@example.com',
                phone: '5555555555',
                address: '789 Oak St, Metropolis, USA',
                age: 40,
              },
              {
                id: '5',
                name: 'Charlie Brown',
                email: 'charlie.brown@example.com',
                phone: '1112223333',
                address: '321 Pine St, Gotham, USA',
                age: 22,
              },
            ],
            nodes: [],
          },
        ],
      },
      {
        id: '19',
        name: 'folder 6',
        variant: 'folder',
        nodes: [
          {
            id: '20',
            name: 'file 14',
            variant: 'file',
            data: [
              {
                id: '1',
                name: 'Diana Prince',
                email: 'diana.prince@example.com',
                phone: '4445556666',
                address: '654 Maple St, Star City, USA',
                age: 28,
              },
              {
                id: '2',
                name: 'Ethan Hunt',
                email: 'ethan.hunt@example.com',
                phone: '7778889999',
                address: '987 Cedar St, Central City, USA',
                age: 35,
              },
              {
                id: '3',
                name: 'Fiona Gallagher',
                email: 'fiona.gallagher@example.com',
                phone: '2223334444',
                address: '159 Birch St, Coast City, USA',
                age: 27,
              },
              {
                id: '4',
                name: 'George Costanza',
                email: 'george.costanza@example.co',
                phone: '3334445555',
                address: '753 Walnut St, Smallville, USA',
                age: 31,
              },
              {
                id: '5',
                name: 'Hannah Baker',
                email: 'hannah.baker@example.com',
                phone: '6667778888',
                address: '852 Spruce St, Hill Valley, USA',
                age: 19,
              },
            ],
            nodes: [],
          },
          {
            id: '21',
            name: 'file 15',
            variant: 'file',
            data: [
              {
                id: '1',
                name: 'John Doe12312',
                email: 'john.doe324@example.com',
                phone: '324242423',
                address: '1223 New York, USA',
                age: 56,
              },
              {
                id: '2',
                name: 'Jane Doe243423',
                email: 'jane.doe122@example.com',
                phone: '123213123',
                address: '1223 New Street, USA',
                age: 34,
              },
              {
                id: '3',
                name: 'Ivy League',
                email: 'ivy.league@example.com',
                phone: '5556667777',
                address: '123 Ivy St, Ivy Town, USA',
                age: 29,
              },
              {
                id: '4',
                name: 'Jack Sparrow',
                email: 'jack.sparrow@example.com',
                phone: '8889990000',
                address: '456 Pirate Cove, Caribbean, USA',
                age: 45,
              },
              {
                id: '5',
                name: 'Kara Danvers',
                email: 'kara.danvers@example.com',
                phone: '1112223333',
                address: '789 Fortress St, National City, USA',
                age: 26,
              },
            ],
            nodes: [],
          },
          {
            id: '22',
            name: 'folder 7',
            variant: 'folder',
            nodes: [
              {
                id: '23',
                name: 'folder 8',
                variant: 'folder',
                nodes: [
                  {
                    id: '24',
                    name: 'file 16',
                    variant: 'file',
                    data: [
                      {
                        id: '1',
                        name: 'Leonard William',
                        email: 'leonard.william@example.com',
                        phone: '4445556666',
                        address: '321 Science St, Pasadena, USA',
                        age: 33,
                      },
                      {
                        id: '2',
                        name: 'Monica Geller',
                        email: 'monica.geller@example.com',
                        phone: '7778889999',
                        address: '654 Coffee St, New York, USA',
                        age: 30,
                      },
                      {
                        id: '3',
                        name: 'Nina Williams',
                        email: 'nina.williams@example.com',
                        phone: '2223334444',
                        address: '159 Fighter St, Tokyo, Japan',
                        age: 24,
                      },
                      {
                        id: '4',
                        name: 'Oscar Isaac',
                        email: 'oscar.isaac@example.com',
                        phone: '3334445555',
                        address: '753 Actor St, Hollywood, USA',
                        age: 36,
                      },
                      {
                        id: '5',
                        name: 'Penny Lane',
                        email: 'penny.lane@example.com',
                        phone: '6667778888',
                        address: '852 Music St, Liverpool, UK',
                        age: 22,
                      },
                    ],
                    nodes: [],
                  },
                  {
                    id: '25',
                    name: 'file 17',
                    variant: 'file',
                    data: [
                      {
                        id: '1',
                        name: 'John Doe',
                        email: 'john.doe@example.com',
                        phone: '324242423',
                        address: '1223 New York, USA',
                        age: 12,
                      },
                      {
                        id: '2',
                        name: 'Jane Doe2',
                        email: 'jane.doe12@google.com',
                        phone: '1234567890',
                        address: '123 Main St, Anytown, USA',
                        age: 25,
                      },
                      {
                        id: '3',
                        name: 'Alice Smith',
                        email: 'alice.smith@example.com',
                        phone: '9876543210',
                        address: '456 Elm St, Springfield, USA',
                        age: 30,
                      },
                      {
                        id: '4',
                        name: 'Bob Johnson',
                        email: 'bob.johnson@example.com',
                        phone: '5555555555',
                        address: '789 Oak St, Metropolis, USA',
                        age: 40,
                      },
                      {
                        id: '5',
                        name: 'Charlie Brown',
                        email: 'charlie.brown@example.com',
                        phone: '1112223333',
                        address: '321 Pine St, Gotham, USA',
                        age: 22,
                      },
                    ],
                    nodes: [],
                  },
                  {
                    id: '26',
                    name: 'file 18',
                    variant: 'file',
                    data: [
                      {
                        id: '1',
                        name: 'Diana Prince',
                        email: 'diana.prince@example.com',
                        phone: '4445556666',
                        address: '654 Maple St, Star City, USA',
                        age: 28,
                      },
                      {
                        id: '2',
                        name: 'Ethan Hunt',
                        email: 'ethan.hunt@example.com',
                        phone: '7778889999',
                        address: '987 Cedar St, Central City, USA',
                        age: 35,
                      },
                      {
                        id: '3',
                        name: 'Fiona Gallagher',
                        email: 'fiona.gallagher@example.com',
                        phone: '2223334444',
                        address: '159 Birch St, Coast City, USA',
                        age: 27,
                      },
                      {
                        id: '4',
                        name: 'George Costanza',
                        email: 'george.costanza@example.co',
                        phone: '3334445555',
                        address: '753 Walnut St, Smallville, USA',
                        age: 31,
                      },
                      {
                        id: '5',
                        name: 'Hannah Baker',
                        email: 'hannah.baker@example.com',
                        phone: '6667778888',
                        address: '852 Spruce St, Hill Valley, USA',
                        age: 19,
                      },
                    ],
                    nodes: [],
                  },
                ],
              },
              {
                id: '27',
                name: 'folder 9',
                variant: 'folder',
                nodes: [
                  {
                    id: '28',
                    name: 'file 19',
                    variant: 'file',
                    data: [
                      {
                        id: '1',
                        name: 'John Doe12312',
                        email: 'john.doe324@example.com',
                        phone: '324242423',
                        address: '1223 New York, USA',
                        age: 56,
                      },
                      {
                        id: '2',
                        name: 'Jane Doe243423',
                        email: 'jane.doe122@example.com',
                        phone: '123213123',
                        address: '1223 New Street, USA',
                        age: 34,
                      },
                      {
                        id: '3',
                        name: 'Ivy League',
                        email: 'ivy.league@example.com',
                        phone: '5556667777',
                        address: '123 Ivy St, Ivy Town, USA',
                        age: 29,
                      },
                      {
                        id: '4',
                        name: 'Jack Sparrow',
                        email: 'jack.sparrow@example.com',
                        phone: '8889990000',
                        address: '456 Pirate Cove, Caribbean, USA',
                        age: 45,
                      },
                      {
                        id: '5',
                        name: 'Kara Danvers',
                        email: 'kara.danvers@example.com',
                        phone: '1112223333',
                        address: '789 Fortress St, National City, USA',
                        age: 26,
                      },
                    ],
                    nodes: [],
                  },
                  {
                    id: '29',
                    name: 'file 20',
                    variant: 'file',
                    data: [
                      {
                        id: '1',
                        name: 'Leonard William',
                        email: 'leonard.william@example.com',
                        phone: '4445556666',
                        address: '321 Science St, Pasadena, USA',
                        age: 33,
                      },
                      {
                        id: '2',
                        name: 'Monica Geller',
                        email: 'monica.geller@example.com',
                        phone: '7778889999',
                        address: '654 Coffee St, New York, USA',
                        age: 30,
                      },
                      {
                        id: '3',
                        name: 'Nina Williams',
                        email: 'nina.williams@example.com',
                        phone: '2223334444',
                        address: '159 Fighter St, Tokyo, Japan',
                        age: 24,
                      },
                      {
                        id: '4',
                        name: 'Oscar Isaac',
                        email: 'oscar.isaac@example.com',
                        phone: '3334445555',
                        address: '753 Actor St, Hollywood, USA',
                        age: 36,
                      },
                      {
                        id: '5',
                        name: 'Penny Lane',
                        email: 'penny.lane@example.com',
                        phone: '6667778888',
                        address: '852 Music St, Liverpool, UK',
                        age: 22,
                      },
                    ],
                    nodes: [],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: '30',
        name: 'folder 10',
        variant: 'folder',
        nodes: [
          {
            id: '31',
            name: 'folder 11',
            variant: 'folder',
            nodes: [
              {
                id: '32',
                name: 'file 21',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe',
                    email: 'john.doe@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 12,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe2',
                    email: 'jane.doe12@google.com',
                    phone: '1234567890',
                    address: '123 Main St, Anytown, USA',
                    age: 25,
                  },
                  {
                    id: '3',
                    name: 'Alice Smith',
                    email: 'alice.smith@example.com',
                    phone: '9876543210',
                    address: '456 Elm St, Springfield, USA',
                    age: 30,
                  },
                  {
                    id: '4',
                    name: 'Bob Johnson',
                    email: 'bob.johnson@example.com',
                    phone: '5555555555',
                    address: '789 Oak St, Metropolis, USA',
                    age: 40,
                  },
                  {
                    id: '5',
                    name: 'Charlie Brown',
                    email: 'charlie.brown@example.com',
                    phone: '1112223333',
                    address: '321 Pine St, Gotham, USA',
                    age: 22,
                  },
                ],
                nodes: [],
              },
              {
                id: '33',
                name: 'file 22',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'Diana Prince',
                    email: 'diana.prince@example.com',
                    phone: '4445556666',
                    address: '654 Maple St, Star City, USA',
                    age: 28,
                  },
                  {
                    id: '2',
                    name: 'Ethan Hunt',
                    email: 'ethan.hunt@example.com',
                    phone: '7778889999',
                    address: '987 Cedar St, Central City, USA',
                    age: 35,
                  },
                  {
                    id: '3',
                    name: 'Fiona Gallagher',
                    email: 'fiona.gallagher@example.com',
                    phone: '2223334444',
                    address: '159 Birch St, Coast City, USA',
                    age: 27,
                  },
                  {
                    id: '4',
                    name: 'George Costanza',
                    email: 'george.costanza@example.co',
                    phone: '3334445555',
                    address: '753 Walnut St, Smallville, USA',
                    age: 31,
                  },
                  {
                    id: '5',
                    name: 'Hannah Baker',
                    email: 'hannah.baker@example.com',
                    phone: '6667778888',
                    address: '852 Spruce St, Hill Valley, USA',
                    age: 19,
                  },
                ],
                nodes: [],
              },
              {
                id: '34',
                name: 'file 23',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe12312',
                    email: 'john.doe324@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 56,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe243423',
                    email: 'jane.doe122@example.com',
                    phone: '123213123',
                    address: '1223 New Street, USA',
                    age: 34,
                  },
                  {
                    id: '3',
                    name: 'Ivy League',
                    email: 'ivy.league@example.com',
                    phone: '5556667777',
                    address: '123 Ivy St, Ivy Town, USA',
                    age: 29,
                  },
                  {
                    id: '4',
                    name: 'Jack Sparrow',
                    email: 'jack.sparrow@example.com',
                    phone: '8889990000',
                    address: '456 Pirate Cove, Caribbean, USA',
                    age: 45,
                  },
                  {
                    id: '5',
                    name: 'Kara Danvers',
                    email: 'kara.danvers@example.com',
                    phone: '1112223333',
                    address: '789 Fortress St, National City, USA',
                    age: 26,
                  },
                ],
                nodes: [],
              },
            ],
          },
          {
            id: '35',
            name: 'folder 12',
            variant: 'folder',
            nodes: [
              {
                id: '36',
                name: 'file 24',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'Leonard William',
                    email: 'leonard.william@example.com',
                    phone: '4445556666',
                    address: '321 Science St, Pasadena, USA',
                    age: 33,
                  },
                  {
                    id: '2',
                    name: 'Monica Geller',
                    email: 'monica.geller@example.com',
                    phone: '7778889999',
                    address: '654 Coffee St, New York, USA',
                    age: 30,
                  },
                  {
                    id: '3',
                    name: 'Nina Williams',
                    email: 'nina.williams@example.com',
                    phone: '2223334444',
                    address: '159 Fighter St, Tokyo, Japan',
                    age: 24,
                  },
                  {
                    id: '4',
                    name: 'Oscar Isaac',
                    email: 'oscar.isaac@example.com',
                    phone: '3334445555',
                    address: '753 Actor St, Hollywood, USA',
                    age: 36,
                  },
                  {
                    id: '5',
                    name: 'Penny Lane',
                    email: 'penny.lane@example.com',
                    phone: '6667778888',
                    address: '852 Music St, Liverpool, UK',
                    age: 22,
                  },
                ],
                nodes: [],
              },
              {
                id: '37',
                name: 'file 25',
                variant: 'file',
                data: [
                  {
                    id: '1',
                    name: 'John Doe',
                    email: 'john.doe@example.com',
                    phone: '324242423',
                    address: '1223 New York, USA',
                    age: 12,
                  },
                  {
                    id: '2',
                    name: 'Jane Doe2',
                    email: 'jane.doe12@google.com',
                    phone: '1234567890',
                    address: '123 Main St, Anytown, USA',
                    age: 25,
                  },
                  {
                    id: '3',
                    name: 'Alice Smith',
                    email: 'alice.smith@example.com',
                    phone: '9876543210',
                    address: '456 Elm St, Springfield, USA',
                    age: 30,
                  },
                  {
                    id: '4',
                    name: 'Bob Johnson',
                    email: 'bob.johnson@example.com',
                    phone: '5555555555',
                    address: '789 Oak St, Metropolis, USA',
                    age: 40,
                  },
                  {
                    id: '5',
                    name: 'Charlie Brown',
                    email: 'charlie.brown@example.com',
                    phone: '1112223333',
                    address: '321 Pine St, Gotham, USA',
                    age: 22,
                  },
                ],
                nodes: [],
              },
            ],
          },
        ],
      },
      {
        id: '38',
        name: 'folder 13',
        variant: 'folder',
        nodes: [
          {
            id: '39',
            name: 'file 26',
            variant: 'file',
            data: [
              {
                id: '1',
                name: 'Diana Prince',
                email: 'diana.prince@example.com',
                phone: '4445556666',
                address: '654 Maple St, Star City, USA',
                age: 28,
              },
              {
                id: '2',
                name: 'Ethan Hunt',
                email: 'ethan.hunt@example.com',
                phone: '7778889999',
                address: '987 Cedar St, Central City, USA',
                age: 35,
              },
              {
                id: '3',
                name: 'Fiona Gallagher',
                email: 'fiona.gallagher@example.com',
                phone: '2223334444',
                address: '159 Birch St, Coast City, USA',
                age: 27,
              },
              {
                id: '4',
                name: 'George Costanza',
                email: 'george.costanza@example.co',
                phone: '3334445555',
                address: '753 Walnut St, Smallville, USA',
                age: 31,
              },
              {
                id: '5',
                name: 'Hannah Baker',
                email: 'hannah.baker@example.com',
                phone: '6667778888',
                address: '852 Spruce St, Hill Valley, USA',
                age: 19,
              },
            ],
            nodes: [],
          },
          {
            id: '40',
            name: 'file 27',
            variant: 'file',
            data: [
              {
                id: '1',
                name: 'John Doe12312',
                email: 'john.doe324@example.com',
                phone: '324242423',
                address: '1223 New York, USA',
                age: 56,
              },
              {
                id: '2',
                name: 'Jane Doe243423',
                email: 'jane.doe122@example.com',
                phone: '123213123',
                address: '1223 New Street, USA',
                age: 34,
              },
              {
                id: '3',
                name: 'Ivy League',
                email: 'ivy.league@example.com',
                phone: '5556667777',
                address: '123 Ivy St, Ivy Town, USA',
                age: 29,
              },
              {
                id: '4',
                name: 'Jack Sparrow',
                email: 'jack.sparrow@example.com',
                phone: '8889990000',
                address: '456 Pirate Cove, Caribbean, USA',
                age: 45,
              },
              {
                id: '5',
                name: 'Kara Danvers',
                email: 'kara.danvers@example.com',
                phone: '1112223333',
                address: '789 Fortress St, National City, USA',
                age: 26,
              },
            ],
            nodes: [],
          },
          {
            id: '41',
            name: 'file 28',
            variant: 'file',
            data: [
              {
                id: '1',
                name: 'Leonard William',
                email: 'leonard.william@example.com',
                phone: '4445556666',
                address: '321 Science St, Pasadena, USA',
                age: 33,
              },
              {
                id: '2',
                name: 'Monica Geller',
                email: 'monica.geller@example.com',
                phone: '7778889999',
                address: '654 Coffee St, New York, USA',
                age: 30,
              },
              {
                id: '3',
                name: 'Nina Williams',
                email: 'nina.williams@example.com',
                phone: '2223334444',
                address: '159 Fighter St, Tokyo, Japan',
                age: 24,
              },
              {
                id: '4',
                name: 'Oscar Isaac',
                email: 'oscar.isaac@example.com',
                phone: '3334445555',
                address: '753 Actor St, Hollywood, USA',
                age: 36,
              },
              {
                id: '5',
                name: 'Penny Lane',
                email: 'penny.lane@example.com',
                phone: '6667778888',
                address: '852 Music St, Liverpool, UK',
                age: 22,
              },
            ],
            nodes: [],
          },
        ],
      },
      {
        id: '42',
        name: 'file 29',
        variant: 'file',
        data: [
          {
            id: '1',
            name: 'John Doe',
            email: 'john.doe@example.com',
            phone: '324242423',
            address: '1223 New York, USA',
            age: 12,
          },
          {
            id: '2',
            name: 'Jane Doe2',
            email: 'jane.doe12@google.com',
            phone: '1234567890',
            address: '123 Main St, Anytown, USA',
            age: 25,
          },
          {
            id: '3',
            name: 'Alice Smith',
            email: 'alice.smith@example.com',
            phone: '9876543210',
            address: '456 Elm St, Springfield, USA',
            age: 30,
          },
          {
            id: '4',
            name: 'Bob Johnson',
            email: 'bob.johnson@example.com',
            phone: '5555555555',
            address: '789 Oak St, Metropolis, USA',
            age: 40,
          },
          {
            id: '5',
            name: 'Charlie Brown',
            email: 'charlie.brown@example.com',
            phone: '1112223333',
            address: '321 Pine St, Gotham, USA',
            age: 22,
          },
        ],
        nodes: [],
      },
      {
        id: '43',
        name: 'file 30',
        variant: 'file',
        data: [
          {
            id: '1',
            name: 'Diana Prince',
            email: 'diana.prince@example.com',
            phone: '4445556666',
            address: '654 Maple St, Star City, USA',
            age: 28,
          },
          {
            id: '2',
            name: 'Ethan Hunt',
            email: 'ethan.hunt@example.com',
            phone: '7778889999',
            address: '987 Cedar St, Central City, USA',
            age: 35,
          },
          {
            id: '3',
            name: 'Fiona Gallagher',
            email: 'fiona.gallagher@example.com',
            phone: '2223334444',
            address: '159 Birch St, Coast City, USA',
            age: 27,
          },
          {
            id: '4',
            name: 'George Costanza',
            email: 'george.costanza@example.co',
            phone: '3334445555',
            address: '753 Walnut St, Smallville, USA',
            age: 31,
          },
          {
            id: '5',
            name: 'Hannah Baker',
            email: 'hannah.baker@example.com',
            phone: '6667778888',
            address: '852 Spruce St, Hill Valley, USA',
            age: 19,
          },
        ],
        nodes: [],
      },
      {
        id: '44',
        name: 'file 31',
        variant: 'file',
        data: [
          {
            id: '1',
            name: 'John Doe12312',
            email: 'john.doe324@example.com',
            phone: '324242423',
            address: '1223 New York, USA',
            age: 56,
          },
          {
            id: '2',
            name: 'Jane Doe243423',
            email: 'jane.doe122@example.com',
            phone: '123213123',
            address: '1223 New Street, USA',
            age: 34,
          },
          {
            id: '3',
            name: 'Ivy League',
            email: 'ivy.league@example.com',
            phone: '5556667777',
            address: '123 Ivy St, Ivy Town, USA',
            age: 29,
          },
          {
            id: '4',
            name: 'Jack Sparrow',
            email: 'jack.sparrow@example.com',
            phone: '8889990000',
            address: '456 Pirate Cove, Caribbean, USA',
            age: 45,
          },
          {
            id: '5',
            name: 'Kara Danvers',
            email: 'kara.danvers@example.com',
            phone: '1112223333',
            address: '789 Fortress St, National City, USA',
            age: 26,
          },
        ],
        nodes: [],
      },
    ],
  },
  {
    id: '53',
    name: 'file 38',
    variant: 'file',
    data: [
      {
        id: '1',
        name: 'Leonard William',
        email: 'leonard.william@example.com',
        phone: '4445556666',
        address: '321 Science St, Pasadena, USA',
        age: 33,
      },
      {
        id: '2',
        name: 'Monica Geller',
        email: 'monica.geller@example.com',
        phone: '7778889999',
        address: '654 Coffee St, New York, USA',
        age: 30,
      },
      {
        id: '3',
        name: 'Nina Williams',
        email: 'nina.williams@example.com',
        phone: '2223334444',
        address: '159 Fighter St, Tokyo, Japan',
        age: 24,
      },
      {
        id: '4',
        name: 'Oscar Isaac',
        email: 'oscar.isaac@example.com',
        phone: '3334445555',
        address: '753 Actor St, Hollywood, USA',
        age: 36,
      },
      {
        id: '5',
        name: 'Penny Lane',
        email: 'penny.lane@example.com',
        phone: '6667778888',
        address: '852 Music St, Liverpool, UK',
        age: 22,
      },
    ],
    nodes: [
      {
        id: '54',
        name: 'file 39',
        variant: 'file',
        data: [
          {
            id: '1',
            name: 'John Doe',
            email: 'john.doe@example.com',
            phone: '324242423',
            address: '1223 New York, USA',
            age: 12,
          },
          {
            id: '2',
            name: 'Jane Doe2',
            email: 'jane.doe12@google.com',
            phone: '1234567890',
            address: '123 Main St, Anytown, USA',
            age: 25,
          },
          {
            id: '3',
            name: 'Alice Smith',
            email: 'alice.smith@example.com',
            phone: '9876543210',
            address: '456 Elm St, Springfield, USA',
            age: 30,
          },
          {
            id: '4',
            name: 'Bob Johnson',
            email: 'bob.johnson@example.com',
            phone: '5555555555',
            address: '789 Oak St, Metropolis, USA',
            age: 40,
          },
          {
            id: '5',
            name: 'Charlie Brown',
            email: 'charlie.brown@example.com',
            phone: '1112223333',
            address: '321 Pine St, Gotham, USA',
            age: 22,
          },
        ],
        nodes: [],
      },
      {
        id: '55',
        name: 'file 40',
        variant: 'file',
        data: [
          {
            id: '1',
            name: 'Diana Prince',
            email: 'diana.prince@example.com',
            phone: '4445556666',
            address: '654 Maple St, Star City, USA',
            age: 28,
          },
          {
            id: '2',
            name: 'Ethan Hunt',
            email: 'ethan.hunt@example.com',
            phone: '7778889999',
            address: '987 Cedar St, Central City, USA',
            age: 35,
          },
          {
            id: '3',
            name: 'Fiona Gallagher',
            email: 'fiona.gallagher@example.com',
            phone: '2223334444',
            address: '159 Birch St, Coast City, USA',
            age: 27,
          },
          {
            id: '4',
            name: 'George Costanza',
            email: 'george.costanza@example.co',
            phone: '3334445555',
            address: '753 Walnut St, Smallville, USA',
            age: 31,
          },
          {
            id: '5',
            name: 'Hannah Baker',
            email: 'hannah.baker@example.com',
            phone: '6667778888',
            address: '852 Spruce St, Hill Valley, USA',
            age: 19,
          },
        ],
        nodes: [],
      },
    ],
  },
]
